# ====== BUILD ======
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
# Copie le pom et télécharge les deps (cache)
COPY pom.xml .
RUN mvn -q -B -DskipTests dependency:go-offline
# Copie le code puis build
COPY src ./src
RUN mvn -q -B -DskipTests package

# ====== RUNTIME ======
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
# Copie le jar depuis l'étape build
COPY --from=build /app/target/*.jar app.jar
ENV JAVA_OPTS="-Xms256m -Xmx512m"
EXPOSE 8080
HEALTHCHECK --interval=10s --timeout=3s --retries=10 \
  CMD wget -qO- http://localhost:8080/actuator/health || exit 1
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar app.jar"]
